services:
  syncplay-server:
    image: lucidaeon/syncplay-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8999:8999"
    environment:
     - PASSWORD=
     - TLS=/certs
    volumes:
     - /etc/letsencrypt/live/my.tld:/certs:ro

